### PR TITLE
The value I entered is visible beneath the form

### PR DESCRIPTION
**Pull request by XeniyaDob**
Anya, could you please check AddTodoForm.js line 18?
And comments, on line 16, 17. 
The app working this way ----props.onAddTodo(todoTitle)
Not working this way ---------props.onAddTodo(newTodo)

### CODE REVIEW

**Review by tsbrun — CHANGES_REQUESTED** [review]
Hey, Xeniya. I'll do my best to answer your question. 

So this lab is about React state. We want to store the todo we enter into the form in state as `newTodo` so we can access the state when we need to add a todo, grab `newTodo`, and use that variable to update the todo list. 

While your app still works when you use the variable `todoTitle` because you're grabbing the input from the form, this method bypasses the state. So you need to find a way to access state and grab `newTodo` to use in the `AddTodoForm` component. 

Let me know if this makes sense. And if you can't figure out how to use state, I encourage you to reach out to one of the mentors and have them go through the code with you. It's super tricky and it can take a while to get the hang of, but it's an important concept to understand. 

I hope my explanation helped :)  It sucks sometimes, but debugging is a part of programming, no matter how good you are at it. You can do this!

**Comment by XeniyaDob** [comment]
Hello Anya,
Thank you! I will try to fix this. Will do my best.

**Comment by XeniyaDob** [comment]
Hello Anya,

I was debugging my code. I have useState Hook in my App component and a handler in the AddTodoForm.js. When I console.log({newTodo})in the App.js right under useState() hook it displays my input value. 

 I communicated with one of the mentors Duc Vu and some of my classmates, we discussed this line
 -Inside the handleAddTodo function, invoke the onAddTodo callback prop and pass newTodo as an argument.

He recently helped another student with the same issue and already confirmed the error with Mary Alice. It should be todoTitle instead of newTodo.

Thanks for helping me to dive deep into my code.

**Comment by tsbrun** [comment]
I’m glad you could get it figured out! Finally figuring out the solution to a bug is my favorite part of coding 😊 You can go ahead and merge this branch into `main`.

**Pull request merged**
